## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
server.name: kibana
server.host: "0"

## X-Pack security credentials
elasticsearch.hosts: [ "$ELASTICSEARCH_HOST" ]
elasticsearch.username: elastic
elasticsearch.password: $ELASTICSEARCH_PASSWORD

xpack.monitoring.ui.container.elasticsearch.enabled: true